### ISSUE TITLE
Ability to send file attachments with the message

### ISSUE THREAD

**Issue by dstegelman** [pipozzz/rocket-python#22]
https://docs.rocket.chat/developer-guides/rest-api/chat/postmessage

**Comment by fuzunspm** [comment]
it would be great to send local files instead using file url

**Comment by fuzunspm** [comment]
any update on sending files ?

**Comment by dstegelman** [comment]
Hi,  I'm currently looking for authors to take over this library as I am no longer active in the python or rocket chat communities.  I won't be personally adding any new features myself, but will merge in pull requests until someone is able to take over the repository.

**Comment by infintropy** [comment]
hey Dan. Nice module. If you swap your requests call to use `json=` instead of `data=` in `base.py` your attachment object will transfer properly. I ran into this same issue and switching that one kwarg did the trick.

**Comment by pipozzz** [comment]
> Hi, I'm currently looking for authors to take over this library as I am no longer active in the python or rocket chat communities. I won't be personally adding any new features myself, but will merge in pull requests until someone is able to take over the repository.

Hi,
If you agree, I could take over the repository.

**Comment by pipozzz** [comment]
Fixed this in #28
