### ISSUE TITLE
Bad error handling in auth code

### ISSUE THREAD

**Issue by sergey-shambir** [pipozzz/rocket-python#24]
When RocketChat API disabled, server responds:
```json
{
  "status": "error",
  "message": "API endpoint does not exist"
}
```
In this case library throws an exception from method `set_auth_token` in `base.py`:
```
Traceback
   self.auth_token = response.json()['data']['authToken']
KeyError: 'data'
```

This error doesn't say the real reason of failure.
Can you please add handling of the [response](http://docs.python-requests.org/en/master/api/#requests.Response) object in error state?

The response has following state in my case:
```
response=<Response [405]>
response.text={"status":"error","message":"API endpoint does not exist"}
response.reason=Method Not Allowed
```

**Comment by dstegelman** [comment]
Hi, Thanks for reporting this.  I have very limited time to spend fixing issues, but I am more than happy to accept a pull request.
